Check for nix-env 1.7 in bin/shell before starting.
Summary:
Things go horribly, horribly wrong when using nix-env 1.6 instead of 1.7.
Ideally, this should probably be checked in nix expressions themselves, but
since this is our main entry point, it seems reasonable to add it here for now.

Test Plan:
Changed the grep to '1.6' instead of '1.7' to test, and got the error as
expected.

Reviewers: johnw, austin

Reviewed By: austin

Differential Revision: https://phabricator.haskell.org/D9

diff --git a/bin/shell b/bin/shell
--- a/bin/shell
+++ b/bin/shell
@@ -1,4 +1,13 @@
 #!/bin/sh
+(nix-env --version | grep -q '1.7') || {
+  echo "nix-env 1.7 is required but not found."
+  echo "Update it using \`nix-env -i nix\`, or install nix by following the"
+  echo "instructions here:"
+  echo "http://hydra.nixos.org/build/11758030/download/1/manual/"\
+"#chap-installation"
+  exit 1
+}
+
 canonical=$(cd -P -- "$(dirname -- "$0")" && \
             printf '%s\n' "$(pwd -P)/$(basename -- "$0")")
 AURON_BINDIR=$(dirname -- "$canonical")
